spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flow
    username: Peti
    password: AaAaAaAaAa_*_1
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create-drop

